### ISSUE TITLE
export to set of csv files broken (postgis branch)

### ISSUE THREAD

**Issue by jkall** [jkall/qgis-midvatten-plugin#257]
Affects postgis branch. I think this is of high priority since csv exports currently are the only possible exports from postgis db.  

python error:
AttributeError: 'NoneType' object has no attribute 'fetchall' 
Traceback (most recent call last):
  File "/home/josef/.qgis2/python/plugins/midvatten/midvatten.py", line 395, in export_csv
    exportinstance.export_2_csv(exportfolder)
  File "/home/josef/.qgis2/python/plugins/midvatten/tools/export_data.py", line 43, in export_2_csv
    db_utils.verify_table_exists)
  File "/home/josef/.qgis2/python/plugins/midvatten/tools/export_data.py", line 152, in write_data
    no_of_obs = self.get_number_of_obsids(obsids, tname_with_prefix)
  File "/home/josef/.qgis2/python/plugins/midvatten/tools/export_data.py", line 141, in get_number_of_obsids
    no_of_obs = no_of_obs_cursor.fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'

Python version: 2.7.6 (default, Nov 23 2017, 15:53:45) [GCC 4.8.4] 
QGIS version: 2.14.22-Essen Essen, exported

**Comment by HenrikSpa** [comment]
Fixed. Tested it by exporting some obsids from a postgis db.
