### ISSUE TITLE
Postgis get foreign keys error

### ISSUE THREAD

**Issue by HenrikSpa** [jkall/qgis-midvatten-plugin#276]
2018-08-16T15:40:57	1	Traceback (most recent call last):
			  File "/home/henrik/.qgis2/python/plugins/midvatten/tools/midvatten_utils.py", line 1310, in func_wrapper
			    ret = func(*args, **kwargs)
			  File "/home/henrik/.qgis2/python/plugins/midvatten/tools/midvatten_utils.py", line 1481, in new_func
			    result = func(*args, **kwargs)
			  File "/home/henrik/.qgis2/python/plugins/midvatten/tools/import_data_to_db.py", line 364, in new_func
			    result = func(*args, **kwargs)
			  File "/home/henrik/.qgis2/python/plugins/midvatten/tools/import_general_csv_gui.py", line 186, in start_import
			    foreign_keys = db_utils.get_foreign_keys(goal_table)
			  File "/home/henrik/.qgis2/python/plugins/midvatten/tools/db_utils.py", line 476, in get_foreign_keys
			    res = m.groups()
			AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by HenrikSpa** [comment]
Done in qgis2 and qgis3 branches.
