### ISSUE TITLE
Water quality report error

### ISSUE THREAD

**Issue by JoeFra** [jkall/qgis-midvatten-plugin#294]
Får följande fel när jag försöker ta ut en Water quality report. Felar dock endast för denna obsid (Anv: Hinderstorp), andra obsid går bra. (Projektnr 2962).

2019-01-24T12:36:51     WARNING    Traceback (most recent call last):
              File "C:/Users/joel.AQUAFIRMS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\midvatten.py", line 164, in 
              self.actionwqualreport.triggered.connect(lambda x: self.waterqualityreport())
              File "C:\Users\joel.AQUAFIRMS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\midvatten\tools\midvatten_utils.py", line 1438, in new_func
              result = func(*args, **kwargs)
              File "C:/Users/joel.AQUAFIRMS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\midvatten.py", line 928, in waterqualityreport
              Wqualreport(qgis.utils.iface.activeLayer(),self.ms.settingsdict)#TEMPORARY FOR GVAB
              File "C:\Users\joel.AQUAFIRMS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\midvatten\tools\wqualreport.py", line 74, in __init__
              ReportData = self.GetData(self.settingsdict['database'], obsid, dbconnection) # one observation at a time
              File "C:\Users\joel.AQUAFIRMS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\midvatten\tools\wqualreport.py", line 203, in GetData
              sql += date_time
             TypeError: can only concatenate str (not "NoneType") to str

**Comment by HenrikSpa** [comment]
The issue is that date_time is NULL for one report. I'll check for a solution.
