### ISSUE TITLE
Matplotlib 'Automatic legend placement' Error 

### ISSUE THREAD

**Issue by mabi38** [jkall/qgis-midvatten-plugin#335]
When I ttry creating a time series plot or an XY plot I receive the follwing python error:

Traceback (most recent call last):
              File "C:\Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\midvatten_plugin.py", line 138, in 
              self.actionPlotTS.triggered.connect(lambda x: self.plot_timeseries())
              File "C:\Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\tools\utils\common_utils.py", line 1122, in new_func
              result = func(*args, **kwargs)
              File "C:\Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\midvatten_plugin.py", line 811, in plot_timeseries
              dlg = TimeSeriesPlot(qgis.utils.iface.activeLayer(), self.ms.settingsdict)
              File "C:\Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\tools\tsplot.py", line 42, in __init__
              self.showtheplot(layer)
              File "C:\Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\tools\utils\db_utils.py", line 393, in func_wrapper
              ret = func(*args, **kwargs)
              File "C:\Users/Martin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\midvatten\tools\tsplot.py", line 103, in showtheplot
              leg = fig.legend(p, plabel, loc=0)#leg = fig.legend(p, plabel, 'right')
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\matplotlib\figure.py", line 1958, in legend
              l = mlegend.Legend(self, handles, labels, *extra_args,
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\matplotlib\legend.py", line 461, in __init__
              raise ValueError(

             ValueError: Automatic legend placement (loc='best') not implemented for figure legend.

Did work in the past perfectly, but now? Any idea how to solve the problem? 
Thanks a lot for helpful hints.

Martin

**Comment by HenrikSpa** [comment]
Yes you're correct, XY-plot is only for values vs. values. Once upon a time it was used for presenting results from vlf and seismic measurements (distance as x-axis and ground surface, vlf and seismic measurements as y1, y2 and y3). The Section plot can be used for this now with the added value of stratigraphy bars.

Regards,
Henrik
